This notebook (and the slides from lecture 8) will help you go straight from training a model in Colab to deploying it in a webpage with TensorFlow.js - without having to leave the browser.

Configure this notebook to work with your GitHub account by populating these fields.

In [0]:
#@title
!pip install tensorflowjs

In [0]:
# your github username
USER_NAME = "WendyThe13th" 

# the email associated with your commits
# (may not matter if you leave it as this)
USER_EMAIL = "wendyzmq@mail.bnu.edu.cn" 

# the user token you've created (see the lecture 8 slides for instructions)

# site name
# for example, if my user_name is "foo", then this notebook will create
# a site at https://foo.github.io/hw4/
SITE_NAME = "hw4"

Next, run this cell to configure git.

In [0]:
!git config --global user.email {USER_NAME}
!git config --global user.name  {USER_EMAIL}

Clone your GitHub pages repo (see the lecture 8 slides for instructions on how to create one).

In [0]:
import os
repo_path = USER_NAME + '.github.io'
if not os.path.exists(os.path.join(os.getcwd(), repo_path)):
  !git clone https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io

In [0]:
os.chdir(repo_path)
!git pull

From https://github.com/WendyThe13th/WendyThe13th.github.io
   c8a6236..9b061bd  master     -> origin/master
Already up to date.


Create a folder for your site.

In [0]:
project_path = os.path.join(os.getcwd(), SITE_NAME)
if not os.path.exists(project_path): 
  os.mkdir(project_path)
os.chdir(project_path)

These paths will be used by the converter script.

In [0]:
# DO NOT MODIFY
MODEL_DIR = os.path.join(project_path, "model_js")
if not os.path.exists(MODEL_DIR):
  os.mkdir(MODEL_DIR)

In [0]:
url1 = 'http://www.gutenberg.org/cache/epub/19033/pg19033.txt'
url2 = 'http://www.gutenberg.org/cache/epub/345/pg345.txt'
url3 = 'http://www.gutenberg.org/cache/epub/6130/pg6130.txt'

In [0]:

import urllib
from bs4 import BeautifulSoup


html1 = urllib.request.urlopen(url1).read()
soup1 = BeautifulSoup(html1)
text1 = soup1.get_text()

lines1 = (line.strip() for line in text1.splitlines())
# break multi-headlines into a line each
chunks1 = (phrase.strip() for line in lines1 for phrase in line.split("  "))
# drop blank lines
text1 = '\n'.join(chunk for chunk in chunks1 if chunk)

html2 = urllib.request.urlopen(url2).read()
soup2 = BeautifulSoup(html2)
text2 = soup2.get_text()

lines2 = (line.strip() for line in text2.splitlines())
# break multi-headlines into a line each
chunks2 = (phrase.strip() for line in lines2 for phrase in line.split("  "))
# drop blank lines
text2 = '\n'.join(chunk for chunk in chunks2 if chunk)

html3 = urllib.request.urlopen(url3).read()
soup3 = BeautifulSoup(html3)
text3 = soup3.get_text()

lines3 = (line.strip() for line in text3.splitlines())
# break multi-headlines into a line each
chunks3 = (phrase.strip() for line in lines3 for phrase in line.split("  "))
# drop blank lines
text3 = '\n'.join(chunk for chunk in chunks3 if chunk)



In [0]:

text1=text1.split('.')
book1=[]
for i in text1:
  i=i.replace('\n',' ')
  i=i.replace("\'","’")
  book1.append(i)
  
text2=text2.split('.')
book2=[]
for i in text2:
  i=i.replace('\n',' ')
  i=i.replace("\'","’")
  book2.append(i)
  
  
text3=text3.split('.')
book3=[]
for i in text3:
  i=i.replace('\n',' ')
  i=i.replace("\'","’")
  book3.append(i)


In [0]:
x_train = book1[:500]+book2[:500]+book3[:500]
y_train = [0]*500+[1]*500+[2]*500 # Indicating which book each sentence is from

Tokenize the documents, create a word index (word -> number).

In [0]:
max_len = 20
num_words = 1000
from keras.preprocessing.text import Tokenizer
# Fit the tokenizer on the training data
t = Tokenizer(num_words=num_words)
t.fit_on_texts(x_train)

Using TensorFlow backend.


In [0]:
print(t.word_index)

{'the': 1, 'of': 2, 'and': 3, 'to': 4, 'a': 5, 'in': 6, 'i': 7, 'it': 8, 'that': 9, 'was': 10, 'as': 11, 'is': 12, 'with': 13, 'for': 14, 'she': 15, 'he': 16, 'on': 17, 'which': 18, 'not': 19, 'at': 20, 'his': 21, 'but': 22, 'you': 23, 'had': 24, 'this': 25, 'be': 26, 'all': 27, 'said': 28, 'by': 29, 'or': 30, 'alice': 31, 'my': 32, 'we': 33, 'have': 34, 'so': 35, 'they': 36, 'me': 37, 'are': 38, 'there': 39, 'from': 40, 'were': 41, 'her': 42, 'no': 43, 'if': 44, 'an': 45, 'one': 46, 'when': 47, 'them': 48, 'into': 49, 'could': 50, 'out': 51, 'been': 52, 'very': 53, 'what': 54, 'little': 55, 'some': 56, 'up': 57, 'him': 58, 'down': 59, 'homer': 60, 'then': 61, 'like': 62, 'must': 63, 'time': 64, 'would': 65, 'more': 66, 'their': 67, 'who': 68, 'its': 69, 'has': 70, 'may': 71, 'great': 72, 'than': 73, 'know': 74, 'any': 75, 'do': 76, 'other': 77, 'only': 78, 'us': 79, 'our': 80, 'see': 81, 'will': 82, 'gutenberg': 83, 'went': 84, 'about': 85, 'first': 86, 'here': 87, 'now': 88, 'found':

In [0]:
from keras.preprocessing.sequence import pad_sequences


We will save the word index in metadata. Later, we'll use it to convert words typed in the browser to numbers for prediction.

In [0]:
metadata = {
  'word_index': t.word_index,
  'max_len': max_len,  'vocabulary_size': num_words,
}

Define a model.

In [0]:
embedding_size = 32
n_classes = 3
epochs = 10

import keras
model = keras.Sequential()
model.add(keras.layers.Embedding(num_words, embedding_size, input_shape=(max_len,)))
model.add(keras.layers.LSTM(32))
model.add(keras.layers.Dense(3, activation='softmax'))
model.compile('adam', 'sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 20, 32)            32000     
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_1 (Dense)              (None, 3)                 99        
Total params: 40,419
Trainable params: 40,419
Non-trainable params: 0
_________________________________________________________________


Prepare some training data.

In [0]:
x_train = t.texts_to_sequences(x_train)
x_train = pad_sequences(x_train, maxlen=max_len, padding='post')
print(x_train)

[[588  29  25 ...  43 968 969]
 [ 30 689 162 ... 520  20 462]
 [ 83   0   0 ...   0   0   0]
 ...
 [ 44  33  21 ...   0   0   0]
 [ 20   5 549 ...  75  22  60]
 [800  38   6 ...   6   3 834]]


In [0]:
model.fit(x_train, y_train, epochs=epochs,validation_split = 0.1)

Train on 1350 samples, validate on 150 samples
Epoch 1/10
1350/1350 [==============================] - 4s 3ms/step - loss: 1.0874 - acc: 0.3800 - val_loss: 1.3224 - val_acc: 0.0000e+00
Epoch 2/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.9115 - acc: 0.5267 - val_loss: 1.2757 - val_acc: 0.6600
Epoch 3/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.5305 - acc: 0.8222 - val_loss: 0.6642 - val_acc: 0.8533
Epoch 4/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.3034 - acc: 0.9104 - val_loss: 1.0012 - val_acc: 0.7533
Epoch 5/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.2119 - acc: 0.9348 - val_loss: 0.8312 - val_acc: 0.7867
Epoch 6/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.1589 - acc: 0.9548 - val_loss: 0.7691 - val_acc: 0.8067
Epoch 7/10
1350/1350 [==============================] - 3s 2ms/step - loss: 0.1448 - acc: 0.9607 - val_loss: 1.1035 - val_acc: 0.7467
Epoch 8/10


Demo using the model to make predictions.

In [0]:
test_example = "Left Munich at 8:35 P. M., on 1st May, arriving at Vienna early next morning."
x_test = t.texts_to_sequences([test_example])
x_test = pad_sequences(x_test, maxlen=max_len, padding='post')
print(x_test)

[[193  20 569  17  71  20 381 218 346   0   0   0   0   0   0   0   0   0
    0   0]]


In [0]:
preds = model.predict(x_test)
print(preds)
import numpy as np
print(np.argmax(preds))

[[3.5685105e-03 9.9585611e-01 5.7544862e-04]]
1


Convert the model

In [0]:
import json
import tensorflowjs as tfjs

metadata_json_path = os.path.join(MODEL_DIR, 'metadata.json')
json.dump(metadata, open(metadata_json_path, 'wt'))
tfjs.converters.save_keras_model(model, MODEL_DIR)
print('\nSaved model artifcats in directory: %s' % MODEL_DIR)


Saved model artifcats in directory: /content/WendyThe13th.github.io/hw4/model_js


Write an index.html and an index.js file configured to load our model.

In [0]:
index_html = """
<!doctype html>

<body>
  <style>
    #textfield {
      font-size: 120%;
      width: 60%;
      height: 200px;
    }
  </style>
  <h1>
    Title
  </h1>
  <hr>
  <div class="create-model">
    <button id="load-model" style="display:none">Load model</button>
  </div>
  <div>
    <div>
      <span>Vocabulary size: </span>
      <span id="vocabularySize"></span>
    </div>
    <div>
      <span>Max length: </span>
      <span id="maxLen"></span>
    </div>
  </div>
  <hr>
  <div>
    <select id="example-select" class="form-control">
      <option value="example1">Alice's Adventures in Wonderland</option>
      <option value="example2">Dracula</option>
      <option value="example3">The Iliad</option>
    </select>
  </div>
  <div>
    <textarea id="text-entry"></textarea>
  </div>
  <hr>
  <div>
    <span id="status">Standing by.</span>
  </div>

  <script src='https://cdn.jsdelivr.net/npm/@tensorflow/tfjs/dist/tf.min.js'></script>
  <script src='index.js'></script>
</body>
"""

In [0]:
index_js = """
const HOSTED_URLS = {
  model:
      'model_js/model.json',
  metadata:
      'model_js/metadata.json'
};

const examples = {
  'example1':
      'Alice was beginning to get very tired of sitting by her sister on the bank.',
  'example2':
      'Buda-Pesth seems a wonderful place.',
  'example3':
      'Scepticism was as much the result of knowledge, as knowledge is of scepticism.'      
};

function status(statusText) {
  console.log(statusText);
  document.getElementById('status').textContent = statusText;
}

function showMetadata(metadataJSON) {
  document.getElementById('vocabularySize').textContent =
      metadataJSON['vocabulary_size'];
  document.getElementById('maxLen').textContent =
      metadataJSON['max_len'];
}

function settextField(text, predict) {
  const textField = document.getElementById('text-entry');
  textField.value = text;
  doPredict(predict);
}

function setPredictFunction(predict) {
  const textField = document.getElementById('text-entry');
  textField.addEventListener('input', () => doPredict(predict));
}

function disableLoadModelButtons() {
  document.getElementById('load-model').style.display = 'none';
}

function doPredict(predict) {
  const textField = document.getElementById('text-entry');
  const result = predict(textField.value);
  score_string = "Class scores: ";
  for (var x in result.score) {
    score_string += x + " ->  " + result.score[x].toFixed(3) + ", "
  }
  //console.log(score_string);
  status(
      score_string + ' elapsed: ' + result.elapsed.toFixed(3) + ' ms)');
}

function prepUI(predict) {
  setPredictFunction(predict);
  const testExampleSelect = document.getElementById('example-select');
  testExampleSelect.addEventListener('change', () => {
    settextField(examples[testExampleSelect.value], predict);
  });
  settextField(examples['example1'], predict);
}

async function urlExists(url) {
  status('Testing url ' + url);
  try {
    const response = await fetch(url, {method: 'HEAD'});
    return response.ok;
  } catch (err) {
    return false;
  }
}

async function loadHostedPretrainedModel(url) {
  status('Loading pretrained model from ' + url);
  try {
    const model = await tf.loadModel(url);
    status('Done loading pretrained model.');
    disableLoadModelButtons();
    return model;
  } catch (err) {
    console.error(err);
    status('Loading pretrained model failed.');
  }
}

async function loadHostedMetadata(url) {
  status('Loading metadata from ' + url);
  try {
    const metadataJson = await fetch(url);
    const metadata = await metadataJson.json();
    status('Done loading metadata.');
    return metadata;
  } catch (err) {
    console.error(err);
    status('Loading metadata failed.');
  }
}

class Classifier {

  async init(urls) {
    this.urls = urls;
    this.model = await loadHostedPretrainedModel(urls.model);
    await this.loadMetadata();
    return this;
  }

  async loadMetadata() {
    const metadata =
        await loadHostedMetadata(this.urls.metadata);
    showMetadata(metadata);
    this.maxLen = metadata['max_len'];
    console.log('maxLen = ' + this.maxLen);
    this.wordIndex = metadata['word_index']
  }

  predict(text) {
    // Convert to lower case and remove all punctuations.
    const inputText =
        text.trim().toLowerCase().replace(/(\.|\,|\!)/g, '').split(' ');
    // Look up word indices.
    const inputBuffer = tf.buffer([1, this.maxLen], 'float32');
    for (let i = 0; i < inputText.length; ++i) {
      const word = inputText[i];
      inputBuffer.set(this.wordIndex[word], 0, i);
      //console.log(word, this.wordIndex[word], inputBuffer);
    }
    const input = inputBuffer.toTensor();
    //console.log(input);

    status('Running inference');
    const beginMs = performance.now();
    const predictOut = this.model.predict(input);
    //console.log(predictOut.dataSync());
    const score = predictOut.dataSync();//[0];
    predictOut.dispose();
    const endMs = performance.now();

    return {score: score, elapsed: (endMs - beginMs)};
  }
};

async function setup() {
  if (await urlExists(HOSTED_URLS.model)) {
    status('Model available: ' + HOSTED_URLS.model);
    const button = document.getElementById('load-model');
    button.addEventListener('click', async () => {
      const predictor = await new Classifier().init(HOSTED_URLS);
      prepUI(x => predictor.predict(x));
    });
    button.style.display = 'inline-block';
  }

  status('Standing by.');
}

setup();
"""

In [0]:
with open('index.html','w') as f:
  f.write(index_html)
  
with open('index.js','w') as f:
  f.write(index_js)


In [0]:
!ls

index.html  index.js  model_js


Commit and push everything. Note: we're storing large binary files in GitHub, this isn't ideal (if you want to deploy a model down the road, better to host it in a cloud storage bucket).

In [0]:
!git add . 
!git commit -m "colab -> github"
!git push https://{USER_NAME}:{TOKEN}@github.com/{USER_NAME}/{USER_NAME}.github.io/ master

[master 3c69b2e] colab -> github
 1 file changed, 0 insertions(+), 0 deletions(-)
 rewrite hw4/model_js/group1-shard1of1 (97%)
Counting objects: 5, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 146.80 KiB | 13.34 MiB/s, done.
Total 5 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/WendyThe13th/WendyThe13th.github.io/
   9b061bd..3c69b2e  master -> master


All done! Hopefully everything worked. You may need to wait a few moments for the changes to appear in your site. If not working, check the JavaScript console for errors (in Chrome: View -> Developer -> JavaScript Console).

In [0]:
print("Now, visit https://%s.github.io/%s/" % (USER_NAME, SITE_NAME))

Now, visit https://WendyThe13th.github.io/hw4/


If you are debugging and Chrome is failing to pick up your changes, though you've verified they're present in your GitHub repo, see the second answer to: https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome